### ISSUE TITLE
Accuracy Tests

### ISSUE THREAD

**Issue by Buddybenj** [0ldsk00l/nestopia#119]
Not exactly an issue, but I was wondering if there are any plans to improve accuracy so some more of these accuracy tests are passed: http://tasvideos.org/EmulatorResources/NESAccuracyTests.html

Nestopia is still considered by many the most accurate NES emulator out there, however recently some other open-source emulators (e.g. BizHawk) have surpassed Nestopia in number of tests passed (I know accuracy tests don't exactly correlate to accuracy in practice, but accuracy tests are the best at demonstrating differences between emulators and hardware).

**Comment by rdanbrook** [comment]
In an ideal world, yes, accuracy will be improved. That list is actually not completely accurate either, since Nestopia does actually pass tvpassfail now, when using the NTSC filter.

One of the big issues is that Nestopia was written in C++. Heavily abstracted C++ is extremely difficult for a human to parse. I started writing a new emulator in C on the side, maybe it will one day be good enough to replace Nestopia.

I'm hoping to rewrite the APU at some point, that's where a lot of the problems are. I'm not quite ready to do that yet though.

**Comment by Buddybenj** [comment]
OK, thanks for letting me know about the tvpassfail. I have edited the page to reflect that. Are there any other corrections?

**Comment by joepogo** [comment]
Hey rdanbrook! been a while my friend! ill hop on chat so we can discuss this soon. Im going over some of the things nestopia has failed on and i think some of them will probably be easier to fix. At least now with the recent changes it moved up to 80% where it was at 78 or 79 i think. What do you say? Besides getting dracula II fds conversion to work i think we can knock out a few rather easy! :)

**Comment by rdanbrook** [comment]
These tests now pass:
cpu_reset/ram_after_reset
cpu_reset/registers

I can make it pass a lot more CPU tests, since I know a decent amount about the CPU now. I'm going to attempt it and see what happens. I think I just need to implement a few unofficial opcodes.

**Comment by joepogo** [comment]
sweet! cant wait to see the fixes man! great work!

**Comment by Buddybenj** [comment]
Thanks a lot for working on this! I've updated the page.

**Comment by rdanbrook** [comment]
These now pass:
apu_reset/irq_flag_cleared
apu_reset/works_immediately

I'm trying to make apu_reset/4017_written pass too. I am halfway there, but need to do a bit more testing and sifting through code.

**Comment by rdanbrook** [comment]
There will be a major update at some point with lots of accuracy fixes. Stay tuned.
