### ISSUE TITLE
Input lag when activating Vsync

### ISSUE THREAD

**Issue by Danyo119** [0ldsk00l/nestopia#288]
Hello, when I activate Vsync in Nestopia the input lag is really noticeable, its been an issue for years when it comes to Nestopia for me  but I just turn it off.  
PC spec
FX8350 CPU
8gbs Ram
290x GPU AMD
When I turn vsync off everything is fine bar screen tearing.

**Comment by rdanbrook** [comment]
Can you give me some details on your OS?

**Comment by rdanbrook** [comment]
Have you tried using RetroArch? That's the only officially supported way to use Nestopia on Windows at this time, since the old win32 port is unmaintainable.

This could also be an issue you can solve at the driver level. I've never used AMD GPUs on Windows, so I'm not sure what tools exist, but with NVIDIA you have some control over driver settings at least.

**Comment by Danyo119** [comment]
I will try Retroarch, thanks rdanbrook, I will report back.
