### ISSUE TITLE
Compatibility problem with MSI Nahimic 2+

### ISSUE THREAD

**Issue by Roxas84** [0ldsk00l/nestopia#307]
When I lauch games with Nestopia 1.49 with Nahimic installed there is no sound, I have to go on the sound menu then change sound device to make it works. 

When I put sound option on hardware I have a random message "iDirectSound8::CreateSoundBuffer() failed! Sound will be disabled"

Besides nestopia crash almost all the time when I try to change settings especially sounds ones 

When Nahimic is not installed everything work fine but I don't want to remove nahimic .

Please check what's wrong

ps : I'm on windows 10

**Comment by rdanbrook** [comment]
This problem is out of scope. I can't solve issues related to Nahimic. I am also not actively developing the **legacy** win32 port because it is far too bitrotted to work on without significant efforts to modernize it, and it is a waste of time to work on a codebase for only one OS anyway. For the best experience on Windows, please use the libretro port with RetroArch.
