### ISSUE TITLE
Question: Calling: Quick Load, Quick Save, Pause, Continue externally?

### ISSUE THREAD

**Issue by asdf23** [0ldsk00l/nestopia#323]
Is it possible to map a thing (joystick button, keyboard command, whatever) to call some of Nestopia's commands such as the Quick Load, Quick Save, Pause, and Continue?

I'd like to hit a button to quickly run these commands. Right now (I believe) I must: exit full screen, use mouse to click file, then perhaps I can use arrows keys at this point. Instead I want to hit some shortcut such as Ctrl+4.

Is this possible?

**Comment by rdanbrook** [comment]
It's possible if you modify the source a little bit, since the functions to do quicksave/load simply take an integer as an argument, and you could easily just add new input definitions. Input code is currently terrible and I have rewritten it in another private project, so stay alert and eventually something way better will be coming.
