### ISSUE TITLE
I know Nestopia UE is on hiatus, but any chance for v1.50 Windows Binaries?

### ISSUE THREAD

**Issue by ImSpecial** [0ldsk00l/nestopia#327]
Windows binaries are still at the old v1.49, it would be nice to get the latest v1.50 binaries for this great emulator, R.I.P Nestopia.

Thanks for all your work!

**Comment by rdanbrook** [comment]
If someone else would like to build it, then I would give them my blessing. I don't have a Windows computer at the moment and am operating from a phone and a $130 Linux laptop (no way to run a VM), so it definitely won't be me, at least for a long time.

**Comment by BenjaminSiskoo** [comment]
I could try to build it. But do you have a tutorial to do ti ?

**Comment by bunglegrind** [comment]
Try look for compile windows in the issues search bar (if I remember correctly, you should change some paths). But, take in mind, some of the latest features are not available in the GUI (it's stated somewhere in the issues). Probably, at this point it does not make any sense, you should try with retroarch as frontend.

**Comment by fab1o** [comment]
Wondering if anyone has tried to accomplish this feat yet and could document any efforts. Have you tried @BenjaminSiskoo ?

**Comment by BenjaminSiskoo** [comment]
Not again. Without a real tuto. I guess I can't do it.

**Comment by rdanbrook** [comment]
You need to overlay the nestopia-win32 repo on top of this one and then open the VS2010 project, then do a release build in VS.

**Comment by vibonacci** [comment]
If somebody builds windows releases, please share with the repo.

**Comment by BenjaminSiskoo** [comment]
H @rdanbrook, 

Was  really busy. Thanks for your explanations. Anyway, now, I have an error with zlib h (in VS). I don't know how to handle it.

**Comment by rdanbrook** [comment]
I'm taking the project off maintenance mode. There will be new Windows binaries soonish. That is when I am ready to do the next release with new project goals.

**Comment by ImSpecial** [comment]
Now that Mesen is in archival mode, perhaps indefinitely, I'm glad seeing this getting resurrected. Bring back the champ!

**Comment by rdanbrook** [comment]
@ImSpecial part of the reason I decided to bring this back is because Mesen is on pause, and it really shouldn't be hard to just get some basic builds out. I don't think it should be a big problem to just make simple binaries available for those who want a standalone version of this emulator, which is still somewhat maintained. I'm going to basically leave the Windows code alone, cut the GTK/Linux port down to basics, and just make sure stuff still builds. I'll add whatever changes I think are worthwhile from whatever forks exist, and fix things that are low effort. The emulator is very mature and doesn't really need a lot of work done on it.

**Comment by BenjaminSiskoo** [comment]
Great news :) Thanks for this. Nestopia is special for me (I worked on the translation with Martin). Happy to see Nestopia UE alive :)

**Comment by rdanbrook** [comment]
https://sourceforge.net/projects/nestopiaue/files/1.50/
There are the new Windows binaries for the 1.50 release tag. Enjoy.
I'm going to fix this repo up to make it buildable again easily, because I did have to do some tricks to get this built.
I used sourceforge to host it because that's how I always was doing it and I'm too lazy right now to figure out what a more modern and acceptable way is to release Windows stuff. I think if I set up CI that will take care of that problem.

**Comment by BenjaminSiskoo** [comment]
Thanks a lot :)

you should change the copyright too : 2012-2016 R. Danbrook --> 2012-2020 R. Danbrook ?

**Comment by ImSpecial** [comment]
Also I noticed no version number in the details tab, its whatever but kinda weird. (maybe this has always been the case?)
https://i.imgur.com/YK44iTZ.png

**Comment by lwcorp** [comment]
> Also I noticed no version number in the details tab, its whatever but kinda weird. (maybe this has always been the case?)
> https://i.imgur.com/YK44iTZ.png
You can edit your message and just copy paste your image in there.
In any case, I can tell you it always bothered me that it showed x.xx in **Help=>About**:
![image](https://user-images.githubusercontent.com/1773306/101212064-c6906e00-3680-11eb-929c-bb51be6d6a5b.png)

P.S.
While the program alive again, is there any chance to implement #334? I think everyone will enjoy this general feature request.

**Comment by rdanbrook** [comment]
The reason the version is x.xx is because the win32 port was moved to being an "overlay" that could work against any version of the core. It is my intention to maintain both it, and the GTK port in this fashion going forward. It will all make sense in the future, and I think people will be happy with where I am taking the project.

@lwcorp the reason I did not close that issue is because I am still considering how to implement it cleanly :).
