### ISSUE TITLE
[GTK] PAL and Dendy stuck at 60 FPS instead of 50

### ISSUE THREAD

**Issue by eugene-s-nesdev** [0ldsk00l/nestopia#346]
Current GTK build have a bug. Both PAL and Dendy modes stuck at 60 FPS instead of 50, causing glitchy sound.
It happens regardless of whether Vsync OFF/ON
`configuration -> misc -> vsync`
BTW, internal core timings are correct. Timing test-roms work as needed.

Compiled on Linux Mint 19.3
[buildlog.txt](https://github.com/0ldsk00l/nestopia/files/6095442/buildlog.txt)

Also, fullscreen mode doesn't work.
I've use Nvidia 1050Ti (450.80.02 official driver)
punes and fceux compiled from the sources work correctly on this machine.

**Comment by rdanbrook** [comment]
Yeah, things are pretty broken right now because I am going to make major changes. The fullscreen issues and timing issue you're talking about here both come back to the GTK3 OpenGL widget being a little difficult to work with, and the fact that the code is a spaghetti mess. I'm thinking about switching to Qt and rewriting a lot of things, but it might be more effort than it's worth. Maybe GTK4 is a better choice but I need to experiment to really know.

**Comment by eugene-s-nesdev** [comment]
By the way, Rupert Carmichael rewrote that FHorse's patch:
https://gitlab.com/jgemu/nestopia/-/commit/e818797c3d5b2a044fcfbb7484772d2362ac84f2

So 
https://github.com/0ldsk00l/nestopia/issues/338
https://github.com/0ldsk00l/nestopia/issues/339
it's fixed on your branch already

**Comment by rdanbrook** [comment]
@eugene-s-nesdev does fullscreen work better for you now?

**Comment by eugene-s-nesdev** [comment]
No, it still turn to big window without menu:
[fs.zip](https://github.com/0ldsk00l/nestopia/files/6138606/fs.zip)

**Comment by rdanbrook** [comment]
I did some testing last night using a bunch of different desktop environments. What I discovered is that the function to make GTK windows fullscreen works differently depending on the desktop environment, with all kinds of unpredictable results. So basically, it's not usable and I can't release like this. It's totally broken. I checked out FCEUX to see how it's being done there, and they just use GLX directly. This is a dumpster fire. I have to switch toolkit.
