### ISSUE TITLE
Micro Mages?

### ISSUE THREAD

**Issue by adam-becker** [0ldsk00l/nestopia#348]
I am trying to get the game Micro Mages added to the `NstDatabase.xml` file so that 4 player support can be enabled in the libretro core. I believe I've got the proper CRC/SHA1 values, but regardless of what I do, I can never control players 3 and 4.

```xml
<game>
    <peripherals>
        <device type="fourplayer" />
    </peripherals>
    <cartridge system="NES-NTSC" dump="ok" crc="4E6B9078" sha1="93FF8CEC778771C7200F785798E0D1599EE8FEB5">
        <board type="NES-NROM-256" mapper="0">
            <prg size="32k" />
            <chr size="8k" />
            <pad h="1" v="0" />
        </board>
    </cartridge>
</game>
```
Note: The mirroring and system values may not be correct, as I haven't verified them in the header, but this should be very obviously wrong once the game is loaded.

The SHA1 was generated with `tail -c 40960 <micro mages rom> | sha1sum` (skip the iNES header and sum the remaining bytes), the crc32 was generated in a similar fashion but using the `0xEDB88320` polynomial sum.

Both methods used were verified against `Mega Man 2 (USA).nes`, and the results matched what was expected in the database.

Does the libretro core support 4 players?

**Comment by adam-becker** [comment]
Nevermind, it seems the libretro people decided it was a smart idea to bake the database file in.

**Comment by rdanbrook** [comment]
The libretro port should support 4 players. One of the last things I did with the libretro port was "bake in" the XML database, because with all the weird platforms libretro supports, it was hard to get the file into the right location on some of those, and a lot of bug reports stemmed from people not knowing how to do this. Right now it's a massive char array, and I can't remember exactly how I created it, but I might have used `xxd`, so if you can replicate this and modify the libretro port, that's an option. The standalone Windows port lets you load an external database file, so I think you might be able to add that entry and load the new file manually and test with the Windows port. The GTK/Linux port does not support 4 players.

I don't own the game so I can't help you test this. If it does work, it would be great to know so that it can be added.

**Comment by troyjfarrell** [comment]
@clobber [pointed out](https://github.com/OpenEmu/Nestopia-Core/issues/6#issuecomment-807267707) that the [upstream repository](https://gitlab.com/jgemu/nestopia) [added the entry for Micro Mages](https://gitlab.com/jgemu/nestopia/-/commit/8fff696731ffc50e881924cbaebcaffd35bbb0a5) recently.
