### ISSUE TITLE
Castlevania III - Dracula's Curse (USA) bug

### ISSUE THREAD

**Issue by Cibomatto2002** [0ldsk00l/nestopia#356]
on some levels the top of the screen is jumping around here is a .gif of the bug.
![Animation](https://user-images.githubusercontent.com/21169038/134025671-bd727702-a1d2-49ab-bf96-62aa90dbc97f.gif)

**Comment by rdanbrook** [comment]
This is an old problem that I've known about for years and is also reported in the upstream repo, and there's a nesdev topic on it: https://forums.nesdev.org/viewtopic.php?f=3&t=17010&sid=73d14ecd6d2252e4d3c12e22e89f312b

I'm closing this because it's already reported and this project is just about the standalone GUI now. If it's ever fixed the code changes will be merged here though.
