### ISSUE TITLE
Nintendo Switch Pro Controller support?

### ISSUE THREAD

**Issue by zelenooki87** [0ldsk00l/nestopia#425]
I am exceuse for maybe asking inapropriate question in this section, but, I plan to buy this original controller for Nintendo switch and to play Super Mario serial mostly (Wii, Snes, Nes)

(I have MB with Bluetooth support)

Is this thing compatible with latest Nestopia builds? Thank you guys very much in advance!

**Comment by rdanbrook** [comment]
If it works with the latest SDL2, it should work with the cross platform (FLTK) build. I can't tell you if it works on the win32 build, because I don't own one. It might, but you might also need to jump through some hoops to make it work as a DirectInput controller. Basically, support for a specific controller is out of the scope of this project, because this project relies on the underlying support of the operating system and either SDL2 or DirectInput (very old DirectInput).

I'll leave this issue open in case anyone else knows. Maybe I'll buy one if I like what I hear :).

**Comment by zelenooki87** [comment]
Thanks you for claryfing.
I found mapping config for SDL2 here:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/sdl2/Nintendo%20Switch%20Pro%20Controller.cfg
Does it mean it shoud work as expected?

**Comment by rdanbrook** [comment]
Yes, that means it should work as expected. I'll close this, since we do have a definitive answer now, and if anyone wants to use this on the win32 build there will be instructions available somewhere to make it work as a DirectInput device.
